---
title: "JSC370 Final Project"
author: "Razan Ahsan Rifandi"
output: 
    html_document:
        toc: TRUE
        toc_float: TRUE
---

This is my JSC370 Final Project website.

```{r load-data, eval=FALSE, echo=FALSE}
source("process_starbucks_data.R")
```

```{r plot1, class.source="code-r-small"}
p1 <- sb_locs_state |>
  ggplot(aes(x = population, y = n_stores, text = state)) +
  geom_point(size = 3) +
  geom_smooth(method = "lm", se = FALSE, color = "red") +
  labs(
    title = "Number of Starbucks Stores vs State Population",
    x = "Population",
    y = "Number of Starbucks Stores"
  ) +
  theme_minimal()
```

```{r plot2, class.source="code-r-small"}
p2 <- sb_nutr |> 
  ggplot(aes(x = Calories, fill = Category)) +
  geom_histogram(binwidth = 50, alpha = 0.6, position = "identity") +
  labs(
    title = "Caloric Distribution of Starbucks Menu Items",
    x = "Calories",
    y = "Count",
    fill = "Category"
  ) +
  theme_minimal()
```

## Showcasing plots {.tabset}

### Starbucks Stores vs Population

```{r echo=FALSE}
ggplotly(p1, tooltip = c("text", "x", "y"))
```

### Caloric Distribution

```{r echo=FALSE}
ggplotly(p2)
```

{-}